### ISSUE TITLE
documentation fixes.

### ISSUE THREAD

**Issue by mercyground** [milleruk/TraefikStack#1]
edits:
cp /shared/authelia/configuration-copy.yml /shared/authelia/configuration.yml

cp /shared/authelia/users_database-copy.yml /shared/authelia/users_database.yml

#remove first slash from /shared on all 

Additions:
 cp .env.example .env #insert above edit .env to reflect variables

#.env updated with examples
`ACME_DOMAIN_NAME=example.com #your domain 
ACME_EMAIL=email@example.com #contact email for letsencrypt

SHARED_STORAGE=shared/
RULES_STORAGE=rules/
CERT_STORAGE=/data/certs? #am told extract with cert extractor and host on local storage.

##### NOTIFICATIONS
TGRAM_BOT_TOKEN=
TGRAM_CHAT_ID=`

**Comment by milleruk** [comment]
This has been added and updated in the README.MD

#e13143ab0ce96df74efa89e8d3da02f98a187b41

**Comment by milleruk** [comment]
Commit e13143ab0ce96df74efa89e8d3da02f98a187b41 closes #1

**Comment by milleruk** [comment]
Updated Readme to reflect
